# ECE6607
# Processing the weather station data with R
# Arthor: bitmingw
# Created: 29 Oct 2015
# Updated: 30 Oct 2015

# Execute the file by typing
# `source("weather_cor_analysis.R", print.eval = TRUE)`
# In R console

# Reference: all the variable names ("Time" is generated by us)
# [1] "Sample.Time"               "Temperature"               "Wind.Chill"                "HEAT_INDEX"               
# [5] "DEW_POINT"                 "DEGREE_DAY"                "DENSITY_ALTITUDE"          "AVG_TEMP_TODAY"           
# [9] "WET_BULB_GLOBE_TEMP"       "SAT_VAPOR_PRESSURE"        "VAPOR_PRESSURE"            "DRY_AIR_PRESSURE"         
#[13] "DRY_AIR_DENSITY"           "ABSOLUTE_HUMIDITY"         "AIR_DENSITY_RATIO"         "ADJUSTED_ALTITUDE"        
#[17] "SAE_CORRECTION_FACTOR"     "WET_AIR_DENSITY"           "WET_BULB_TEMPERATURE"      "REL_HUMIDITY"             
#[21] "Avg.Wind.Speed"            "WIND_SPEED_MX"             "WIND_SPEED_MN"             "RAW_WIND_DIR"             
#[25] "RAW_WIND_DIR_AV"           "RAW_WIND_DIR_MX"           "RAW_WIND_DIR_MN"           "SEC3_ROLL_AVG_WIND_SPEED" 
#[29] "SEC3_ROLL_AVG_WIND_DIR"    "MIN2_ROLL_AVG_WIND_SPEED"  "MIN2_ROLL_AVG_WIND_DIR"    "MIN10_ROLL_AVG_WIND_SPEED"
#[33] "MIN10_ROLL_AVG_WIND_DIR"   "MIN60_WIND_GUST_DIR"       "MIN60_WIND_GUST_SPEED"     "MIN10_WIND_GUST_DIR"      
#[37] "MIN10_WIND_GUST_SPEED"     "RAIN_TODAY"                "RAINT_THIS_WEEK"           "RAINT_THIS_MONTH"         
#[41] "RAINT_THIS_YEAR"           "RAIN_RATE"                 "RAIN_LAST_HR"              "PRECIP_TYPE"              
#[45] "RAW_BAROM_PRESS"           "ADJ_BAROM_PRESS"           "Time"

# The following variables seems to be fundamental
# "Sample.Time", "Temperature", "VAPOR_PRESSURE", "DRY_AIR_PRESSURE", "WET_AIR_DENSITY"? ...

# Load libraries
library(ggplot2)
library(caTools)
library(reshape) # don't use reshape2 since it has bug for melt function

# Assume the data and the script are in the working directory
wdata <- read.csv("data2.csv", stringsAsFactors = FALSE)

# Convert time string to POSIX time
wdata$Sample.Time <- paste("2015-08-13", wdata$Sample.Time)
wdata$Time <- strptime(wdata$Sample.Time, "%Y-%m-%d %H:%M:%S")

# Draw a plot about the temperature vs time
#ggplot(wdata, aes(Time, Temperature)) + geom_line() + labs(title = "Temperature in One Day")

# Explore the data correlation
# Split the data set into 2 parts
set.seed(6607)
split.vec <- sample.split(wdata[,1], 2/3)
train.set <- subset(wdata, split.vec)
test.set <- subset(wdata, !split.vec)

# Build linear model to explore the Wind.Chill variable
wind.chill.mod <- lm(Wind.Chill ~ Temperature + Avg.Wind.Speed, data = train.set)
summary(wind.chill.mod)
p.Wind.Chill <- predict(wind.chill.mod, newdata = test.set)
wind.chill.data <- cbind(test.set[c("Time", "Wind.Chill")], p.Wind.Chill)
wind.chill.melt <- melt(wind.chill.data, id.vars = c("Time"))
wind.chill.plot <- ggplot(wind.chill.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Wind Chill")
wind.chill.plot

# Build linear model to explore the HEAT_INDEX variable
heat.index.mod <- lm(HEAT_INDEX ~ Temperature + VAPOR_PRESSURE, data = train.set)
summary(heat.index.mod)
p.heat.index <- predict(heat.index.mod, newdata = test.set)
heat.index.data <- cbind(test.set[c("Time", "HEAT_INDEX")], p.heat.index)
heat.index.melt <- melt(heat.index.data, id.vars = c("Time"))
heat.index.plot <- ggplot(heat.index.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Heat Index")
heat.index.plot

# Build linear model to explore the DEW_POINT variable
# NOT ACCURATE, NEED FURTHER STUDY
dew.point.mod <- lm(DEW_POINT ~ Temperature + VAPOR_PRESSURE, data = train.set)
summary(dew.point.mod)
p.dew.point <- predict(dew.point.mod, newdata = test.set)
dew.point.data <- cbind(test.set[c("Time", "DEW_POINT")], p.dew.point)
dew.point.melt <- melt(dew.point.data, id.vars = c("Time"))
dew.point.plot <- ggplot(dew.point.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Dew Point")
dew.point.plot

# Build linear model to explore the DEGREE_DAY variable
degree.day.mod <- lm(DEGREE_DAY ~ AVG_TEMP_TODAY, data = train.set)
summary(degree.day.mod)
p.degree.day <- predict(degree.day.mod, newdata = test.set)
degree.day.data <- cbind(test.set[c("Time", "DEGREE_DAY")], p.degree.day)
degree.day.melt <- melt(degree.day.data, id.vars = c("Time"))
degree.day.plot <- ggplot(degree.day.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Degree Day")
degree.day.plot

# Build linear model to explore the DENSITY_ALTITUDE variable
density.altitude.mod <- lm(DENSITY_ALTITUDE ~ WET_AIR_DENSITY, data = train.set)
summary(density.altitude.mod)
p.density.altitude <- predict(density.altitude.mod, newdata = test.set)
density.altitude.data <- cbind(test.set[c("Time", "DENSITY_ALTITUDE")], p.density.altitude)
density.altitude.melt <- melt(density.altitude.data, id.vars = c("Time"))
density.altitude.plot <- ggplot(density.altitude.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Density Altitude")
density.altitude.plot

# NOTE: AVG_TEMP_TODAY is determined by Temperature with ARMA model
# TODO: generate AVG_TEMP_TODAY from Temperature

# Build linear model to explore the WET_BULB_GLOBE_TEMP variable
wet.bulb.globe.mod <- lm(WET_BULB_GLOBE_TEMP ~ Temperature + VAPOR_PRESSURE, data = train.set)
summary(wet.bulb.globe.mod)
p.wet.bulb.globe <- predict(wet.bulb.globe.mod, newdata = test.set)
wet.bulb.globe.data <- cbind(test.set[c("Time", "WET_BULB_GLOBE_TEMP")], p.wet.bulb.globe)
wet.bulb.globe.melt <- melt(wet.bulb.globe.data, id.vars = c("Time"))
wet.bulb.globe.plot <- ggplot(wet.bulb.globe.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Wet Bulb Globe Temperature")
wet.bulb.globe.plot

# Build linear model to explore the SAT_VAPOR_PRESSURE variable
sat.vapor.pressure.mod <- lm(SAT_VAPOR_PRESSURE ~ Temperature, data = train.set)
summary(sat.vapor.pressure.mod)
p.sat.vapor.pressure <- predict(sat.vapor.pressure.mod, newdata = test.set)
sat.vapor.pressure.data <- cbind(test.set[c("Time", "SAT_VAPOR_PRESSURE")], p.sat.vapor.pressure)
sat.vapor.pressure.melt <- melt(sat.vapor.pressure.data, id.vars = c("Time"))
sat.vapor.plot <- ggplot(sat.vapor.pressure.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Saturated Vapor Pressure")
sat.vapor.plot

# Build linear model to explore the DRY_AIR_DENSITY variable
dry.air.density.mod <- lm(DRY_AIR_DENSITY ~ Temperature, data = train.set)
summary(dry.air.density.mod)
p.dry.air.density <- predict(dry.air.density.mod, newdata = test.set)
dry.air.density.data <- cbind(test.set[c("Time", "DRY_AIR_DENSITY")], p.dry.air.density)
dry.air.density.melt <- melt(dry.air.density.data, id.vars = c("Time"))
dry.air.density.plot <- ggplot(dry.air.density.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Dry Air Density")
dry.air.density.plot

# Build linear model to explore the ABSOLUTE_HUMIDITY variable
abs.humidity.mod <- lm(ABSOLUTE_HUMIDITY ~ DRY_AIR_PRESSURE + VAPOR_PRESSURE, data = train.set)
summary(abs.humidity.mod)
p.abs.humidity <- predict(abs.humidity.mod, newdata = test.set)
abs.humidity.data <- cbind(test.set[c("Time", "ABSOLUTE_HUMIDITY")], p.abs.humidity)
abs.humidity.melt <- melt(abs.humidity.data, id.vars = c("Time"))
abs.humidity.plot <- ggplot(abs.humidity.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Absolute Humidity")
abs.humidity.plot

# NOTE: by definition AIR_DENSITY_RATIO = DRY_AIR_DENSITY / WET_AIR_DENSITY
# It is easy to verify that the R-squared value is 1 for this formula

# Build linear model to explore ADJUSTED_ALTITUDE variable
# NOTE: since DENSITY_ALTITUDE ~ WET_AIR_DENSITY, we guess it is the same case for adjusted altitude
adj.altitude.mod <- lm(ADJUSTED_ALTITUDE ~ WET_AIR_DENSITY, data = train.set)
summary(adj.altitude.mod)
p.adj.altitude <- predict(adj.altitude.mod, newdata = test.set)
adj.altitude.data <- cbind(test.set[c("Time", "ADJUSTED_ALTITUDE")], p.adj.altitude)
adj.altitude.melt <- melt(adj.altitude.data, id.vars = c("Time"))
adj.altitude.plot <- ggplot(adj.altitude.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Adjusted Altitude")
adj.altitude.plot

# NOTE: SAE_CORRECTION_FACTOR is a variable in range (0.97 - 1.01), which has not significant meaning
# We will ignore the discussion for this variable

# Build linear model to explore WET_AIR_DENSITY variable
# NOTE: since DRY_AIR_DENSITY ~ Temperature, we guess it is the same case for wet air
wet.air.density.mod <- lm(WET_AIR_DENSITY ~ Temperature, data = train.set)
summary(wet.air.density.mod)
p.wet.air.density <- predict(wet.air.density.mod, newdata = test.set)
wet.air.density.data <- cbind(test.set[c("Time", "WET_AIR_DENSITY")], p.wet.air.density)
wet.air.density.melt <- melt <- melt(wet.air.density.data, id.vars = c("Time"))
wet.air.density.plot <- ggplot(wet.air.density.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Wet Air Density")
wet.air.density.plot

# Build linear model to explore WET_BULB_TEMPERATURE variable
wet.bulb.temp.mod <- lm(WET_BULB_TEMPERATURE ~ Temperature + VAPOR_PRESSURE, data = train.set)
summary(wet.bulb.temp.mod)
p.wet.bulb.temp <- predict(wet.bulb.temp.mod, newdata = test.set)
wet.bulb.data <- cbind(test.set[c("Time", "WET_BULB_TEMPERATURE")], p.wet.bulb.temp)
wet.bulb.melt <- melt(wet.bulb.data, id.vars = c("Time"))
wet.bulb.plot <- ggplot(wet.bulb.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Wet Bulb Temperature")
wet.bulb.plot

# Build linear model to explore REL_HUMIDITY variable
real.humidity.mod <- lm(REL_HUMIDITY ~ DRY_AIR_PRESSURE + WET_AIR_DENSITY + Temperature, data = train.set)
summary(real.humidity.mod)
p.real.humidity <- predict(real.humidity.mod, newdata = test.set)
real.humidity.data <- cbind(test.set[c("Time", "REL_HUMIDITY")], p.real.humidity)
real.humidity.melt <- melt(real.humidity.data, id.vars = c("Time"))
real.humidity.plot <- ggplot(real.humidity.melt, aes(x = Time, y = value, color = variable)) + geom_line() +
    labs(title = "True Value vs. Prediction for Real Humidity")
real.humidity.plot

